shortName: dummytest
fullName: DummyTest
repo: https://github.com/validatedpatterns/dummytest
webHookName: ''
owners:
  - mlabonte
triggers:
  branches:
  - name: main
    versions:
    - '4.19'

  openshift:
  - version: '4.19'
    branch: main
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: none
    branch: none
